name: ml-precip
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.12.0
  - anyio=3.1.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - async_generator=1.10
  - atk-1.0=2.36.0
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.0
  - bokeh=2.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cartopy=0.19.0.post1
  - certifi=2021.5.30
  - cffi=1.14.5
  - cfgrib=0.9.9.0
  - cftime=1.5.0
  - chardet=4.0.0
  - click=8.0.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - colorcet=2.0.6
  - cryptography=3.4.7
  - curl=7.77.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.5.1
  - dask-core=2021.5.1
  - dataclasses=0.8
  - decorator=5.0.9
  - defusedxml=0.7.1
  - distributed=2021.5.1
  - eccodes=2.22.0
  - entrypoints=0.3
  - eofs=1.4.0
  - expat=2.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=2021.5.0
  - gast=0.4.0
  - gdk-pixbuf=2.42.6
  - geos=3.9.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - graphviz=2.47.2
  - grpcio=1.38.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h5py=3.2.1
  - harfbuzz=2.8.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.14.5
  - hvplot=0.7.3
  - icu=68.1
  - idna=2.10
  - importlib-metadata=4.4.0
  - ipykernel=5.5.5
  - ipython=7.24.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.8.0
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.0
  - jupyterlab_widgets=1.0.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libcxx=11.1.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgd=2.3.2
  - libglib=2.68.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libprotobuf=3.17.1
  - librsvg=2.50.5
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzip=1.7.3
  - llvm-openmp=11.1.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - msgpack-python=1.0.2
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nbserverproxy=0.8.8
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf4=1.5.6
  - notebook=6.4.0
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.14.0.1
  - pandocfilters=1.4.2
  - panel=0.12.1
  - pango=1.48.5
  - param=1.11.1
  - parso=0.8.2
  - partd=1.2.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - pixman=0.40.0
  - proj=7.2.0
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - proplot=0.8.1
  - protobuf=3.17.1
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-eccodes=2021.03.0
  - python_abi=3.7
  - pytz=2021.1
  - pyviz_comms=2.1.0
  - pyyaml=5.4.1
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.25.1
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.16.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - sqlite=3.35.5
  - statsmodels=0.12.2
  - tblib=1.7.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - terminado=0.10.0
  - testpath=0.5.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xarray=0.18.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - future==0.18.2
    - iniconfig==1.1.1
    - innvestigate==1.0.9
    - keras==2.2.4
    - pluggy==0.13.1
    - py==1.10.0
    - pytest==6.2.4
    - toml==0.10.2
