name: ml-precip
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.19.0.post1
  - eofs
  - h5py=2.10.0
  - jupyterlab
  - netcdf4
  - matplotlib=3.4.2
  - pip
  - proplot=0.8.1
  - python=3.7.10
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow=1.13.1
  - xarray=0.18.2
  - xskillscore
  - pip:
    - innvestigate==1.0.9
    - keras==2.2.4
